<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
          DB::table('posts')->insert([
          [
            'title' => '杉戸天然温泉',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 62,
            'zip' => '345-0036',
            'prefecture' => '埼玉県',
            'address' => '埼玉県北葛飾郡杉戸町杉戸2517',
            'access' => '東武伊勢崎線「東武動物公園駅（東口）」より送迎バスあり\n圏央道　幸手ICから約7分。\n東北自動車道 岩槻ＩＣから約30分。久喜ICから約20分。',
            'parking' => '170台(無料）',
            'content' => '埼玉県は東部。周囲を田園に囲まれたのどかな風景の中につくられた大露天風呂。四季を通じて味わえる美しい木々と杉戸の広い空を眺めながら、天然のなめらかな湯と自然を満喫して下さい。 露天風呂は、身体を芯から温められる「源泉あつ湯」、のんびりと贅沢に利用できる「生源泉つぼ風呂・石風呂」、きめ細かい炭酸ガスを天然温泉に溶かしこんだ「高濃度炭酸温泉」、他にも「岩風呂」「寝湯・寝ころび湯」と多彩。快適な湯めぐりをお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '美楽温泉 SPA-HERBS',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0813',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市北区植竹町１丁目８１６−８',
            'access' => 'JR「土呂駅」から徒歩9分。JR大宮駅より無料シャトルバスあり。旧中山道（県道164号線）上尾方面へ。さいたま市北区役所交差点右折し、ステラタウン前',
            'parking' => '180台',
            'content' => 'SPA-HERBSが目指したのは、上質な癒やしと楽しいひとときのコラボレーション。天然温泉はもちろん、各種リラクゼーションサービス、専門店に勝るとも劣らない食事処＆カフェ、楽しく汗をかくフィットネス。盛りだくさんなメニューで一日中楽しめる、それが美楽温泉 SPA-HERBS最大の魅力。美楽な一日をお過ごしいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'さいたま清河寺温泉',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0048',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市西区清河寺683-4',
            'access' => 'JR川越線西大宮駅北口 徒歩18分、大宮駅西口東武バス8番のりば平方行き清河寺下車 徒歩1分。首都高速5号線大宮方面さいたま大宮線与野出口直進約6KM日進南交差点左折',
            'parking' => '200台',
            'content' => '露天風呂にある生源泉湯は、地下約1500mから湧出した38.3度の源泉を掛け流しで利用しております。身体がよく温まり、お肌がすべすべになる泉質です。開放感あふれる緑のロケーション、そして真心込めたおもてなしで、皆様のお越しをお待ちしております',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => 'おふろcafé utatane',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0815',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市北区大成町4丁目179-3',
            'access' => '大宮駅より埼玉新都市交通「ニューシャトル」 鉄道博物館駅（大成駅）より線路沿いを北に向かって徒歩約10分。国道17号線「大成橋南側」信号すぐ 首都高速「与野JCT」から約10分。 東北自動車道「岩槻IC」から約20分',
            'parking' => '有（無料）',
            'content' => 'あたたかいお風呂、おいしいごはん、ふかふかのソファー、明るい音楽。心とカラダがあたたまり、満ち足りる。誰もが特別な時間を過ごせるutataneで、笑顔あふれる素敵なひと時を。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '北浦和公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 1,
            'zip' => '330-0061',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市浦和区常盤9-30-1',
            'access' => 'JR北浦和駅西口から徒歩2分',
            'parking' => '近くの市営駐車場(有料)がご利用いただけます。',
            'content' => 'JR北浦和駅西口から徒歩2分の市街地に位置しています。昭和46年、埼玉大学の移転に伴い、大学跡地を公園として整備する計画が立てられました。昭和48年から整備をはじめ、翌49年に開設されました。また、昭和57年には、公園内に県立近代美術館がオープンしました。北浦和公園の南側はさいたま市の公園と接しており、2つの公園が一体となって公園が形成されています。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '見沼自然公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 1,
            'zip' => '336-0973',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市緑区大字南部領辻450−１',
            'access' => 'JR「大宮駅」東口から国際興業バス「さいたま東営業所行き」「浦和美園駅西口行き」「浦和学院高校行き」「浦和東高校行き」乗車　「締切橋バス停」下車　徒歩約5分。JR「浦和駅」東口から「市立病院経由さいたま東営業所行き」乗車　「締切橋バス停」下車　徒歩約5分。埼玉高速鉄道「浦和美園駅」西口から国際興業バス「大宮駅東口行き」乗車　「締切橋バス停」下車　徒歩約5分',
            'parking' => '198台',
            'content' => 'さいたま市（旧大宮市・旧浦和市エリア）から川口市の埼玉県の中心部に広がる広大な田園地帯は、通称「見沼たんぼ」と呼ばれています。広大な「見沼たんぼ」にはすばらしい公園がたくさんあります。南部分に位置する「見沼自然公園」もそのひとつです。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '東武動物公園',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 61,
            'zip' => '345-0831',
            'prefecture' => '埼玉県',
            'address' => '埼玉県南埼玉郡宮代町大字須賀110',
            'access' => '東武伊勢崎線東武動物公園駅から徒歩で10分',
            'parking' => '西ゲート（動物園側）直営駐車場は、約3,000台駐車可能です。(有料)',
            'content' => '希少なホワイトタイガーをはじめ、全120種類1200頭の動物たちが飼育されており、エサやりなど動物と触れ合い体験もできて、見て楽しい触れて楽しい動物園です。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '国営武蔵丘陵森林公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 45,
            'zip' => '355-0802',
            'prefecture' => '埼玉県',
            'address' => '埼玉県比企郡滑川町大字山田1920',
            'access' => '東武東上線森林公園駅北口からバスで立正大学行きバスで約7分「滑川中学校」下車徒歩5分　公園南口行きバスで約7分（土日祝のみ） 関越自動車道東松山ICから車で熊谷方面へ約10分',
            'parking' => '有料駐車場あり',
            'content' => '公園内は、日本一大きなエアートランポリンのぽんぽこマウンテンやアスレチックコースなど、家族で体を思いっきり動かして遊べる遊具がたくさんあります。また、都市緑化植物園では、四季折々の風景や木々、草花もお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => 'ムーミンバレーパーク',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 8,
            'zip' => '357-0001',
            'prefecture' => '埼玉県',
            'address' => '埼玉県飯能市宮沢327-6',
            'access' => '飯能駅北口から宮沢湖入り口まで約3km (約10分)。飯能駅からバスで約13分',
            'parking' => '電車でのアクセスは、西武池袋線「飯能駅」北口、JR八高線「東飯能駅」東口から、バスで12分ほど（「東飯能駅」からのバスは土日のみ運行）。車でのアクセスも、圏央道・狭山日高ICから約12分',
            'content' => '「ムーミンバレーパーク」は、都心からおよそ50km、埼玉県の南西部に位置する“水と緑”が豊かな飯能市にオープンしました。森と水に囲まれたフィンランドの風土を演出するのにピッタリのロケーションで、都心から車や電車を使って1時間半ほどで気軽に行けるのも魅力的です。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '岩槻城址公園',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 1,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '川越大師 喜多院',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 2,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '熊谷スポーツ文化公園',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 3,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '川口市リサイクルプラザ',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 4,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 5,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 6,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 7,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 8,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 10,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 11,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 12,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 13,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 14,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 15,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 16,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 17,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 18,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 19,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 20,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 21,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '美楽温泉 SPA-HERBS',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0813',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市北区植竹町１丁目８１６−８',
            'access' => 'JR「土呂駅」から徒歩9分。JR大宮駅より無料シャトルバスあり。旧中山道（県道164号線）上尾方面へ。さいたま市北区役所交差点右折し、ステラタウン前',
            'parking' => '180台',
            'content' => 'SPA-HERBSが目指したのは、上質な癒やしと楽しいひとときのコラボレーション。天然温泉はもちろん、各種リラクゼーションサービス、専門店に勝るとも劣らない食事処＆カフェ、楽しく汗をかくフィットネス。盛りだくさんなメニューで一日中楽しめる、それが美楽温泉 SPA-HERBS最大の魅力。美楽な一日をお過ごしいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '杉戸天然温泉3',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 62,
            'zip' => '345-0036',
            'prefecture' => '埼玉県',
            'address' => '埼玉県北葛飾郡杉戸町杉戸2517',
            'access' => '東武伊勢崎線「東武動物公園駅（東口）」より送迎バスあり\n圏央道　幸手ICから約7分。\n東北自動車道 岩槻ＩＣから約30分。久喜ICから約20分。',
            'parking' => '170台(無料）',
            'content' => '埼玉県は東部。周囲を田園に囲まれたのどかな風景の中につくられた大露天風呂。四季を通じて味わえる美しい木々と杉戸の広い空を眺めながら、天然のなめらかな湯と自然を満喫して下さい。 露天風呂は、身体を芯から温められる「源泉あつ湯」、のんびりと贅沢に利用できる「生源泉つぼ風呂・石風呂」、きめ細かい炭酸ガスを天然温泉に溶かしこんだ「高濃度炭酸温泉」、他にも「岩風呂」「寝湯・寝ころび湯」と多彩。快適な湯めぐりをお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '杉戸天然温泉4',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 62,
            'zip' => '345-0036',
            'prefecture' => '埼玉県',
            'address' => '埼玉県北葛飾郡杉戸町杉戸2517',
            'access' => '東武伊勢崎線「東武動物公園駅（東口）」より送迎バスあり\n圏央道　幸手ICから約7分。\n東北自動車道 岩槻ＩＣから約30分。久喜ICから約20分。',
            'parking' => '170台(無料）',
            'content' => '埼玉県は東部。周囲を田園に囲まれたのどかな風景の中につくられた大露天風呂。四季を通じて味わえる美しい木々と杉戸の広い空を眺めながら、天然のなめらかな湯と自然を満喫して下さい。 露天風呂は、身体を芯から温められる「源泉あつ湯」、のんびりと贅沢に利用できる「生源泉つぼ風呂・石風呂」、きめ細かい炭酸ガスを天然温泉に溶かしこんだ「高濃度炭酸温泉」、他にも「岩風呂」「寝湯・寝ころび湯」と多彩。快適な湯めぐりをお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '杉戸天然温泉5',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 62,
            'zip' => '345-0036',
            'prefecture' => '埼玉県',
            'address' => '埼玉県北葛飾郡杉戸町杉戸2517',
            'access' => '東武伊勢崎線「東武動物公園駅（東口）」より送迎バスあり\n圏央道　幸手ICから約7分。\n東北自動車道 岩槻ＩＣから約30分。久喜ICから約20分。',
            'parking' => '170台(無料）',
            'content' => '埼玉県は東部。周囲を田園に囲まれたのどかな風景の中につくられた大露天風呂。四季を通じて味わえる美しい木々と杉戸の広い空を眺めながら、天然のなめらかな湯と自然を満喫して下さい。 露天風呂は、身体を芯から温められる「源泉あつ湯」、のんびりと贅沢に利用できる「生源泉つぼ風呂・石風呂」、きめ細かい炭酸ガスを天然温泉に溶かしこんだ「高濃度炭酸温泉」、他にも「岩風呂」「寝湯・寝ころび湯」と多彩。快適な湯めぐりをお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '',
            'theme' => '',
            'category_id' => 1,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
        ]);
    }
}
