<?php

use Illuminate\Database\Seeder;

class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
          DB::table('posts')->insert([
          [
            'title' => '杉戸天然温泉',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 62,
            'zip' => '345-0036',
            'prefecture' => '埼玉県',
            'address' => '埼玉県北葛飾郡杉戸町杉戸2517',
            'access' => '東武伊勢崎線「東武動物公園駅（東口）」より送迎バスあり\n圏央道　幸手ICから約7分。\n東北自動車道 岩槻ＩＣから約30分。久喜ICから約20分。',
            'parking' => '170台(無料）',
            'content' => '埼玉県は東部。周囲を田園に囲まれたのどかな風景の中につくられた大露天風呂。四季を通じて味わえる美しい木々と杉戸の広い空を眺めながら、天然のなめらかな湯と自然を満喫して下さい。 露天風呂は、身体を芯から温められる「源泉あつ湯」、のんびりと贅沢に利用できる「生源泉つぼ風呂・石風呂」、きめ細かい炭酸ガスを天然温泉に溶かしこんだ「高濃度炭酸温泉」、他にも「岩風呂」「寝湯・寝ころび湯」と多彩。快適な湯めぐりをお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '美楽温泉 SPA-HERBS',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0813',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市北区植竹町１丁目８１６−８',
            'access' => 'JR「土呂駅」から徒歩9分。JR大宮駅より無料シャトルバスあり。旧中山道（県道164号線）上尾方面へ。さいたま市北区役所交差点右折し、ステラタウン前',
            'parking' => '180台',
            'content' => 'SPA-HERBSが目指したのは、上質な癒やしと楽しいひとときのコラボレーション。天然温泉はもちろん、各種リラクゼーションサービス、専門店に勝るとも劣らない食事処＆カフェ、楽しく汗をかくフィットネス。盛りだくさんなメニューで一日中楽しめる、それが美楽温泉 SPA-HERBS最大の魅力。美楽な一日をお過ごしいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'さいたま清河寺温泉',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0048',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市西区清河寺683-4',
            'access' => 'JR川越線西大宮駅北口 徒歩18分、大宮駅西口東武バス8番のりば平方行き清河寺下車 徒歩1分。首都高速5号線大宮方面さいたま大宮線与野出口直進約6KM日進南交差点左折',
            'parking' => '200台',
            'content' => '露天風呂にある生源泉湯は、地下約1500mから湧出した38.3度の源泉を掛け流しで利用しております。身体がよく温まり、お肌がすべすべになる泉質です。開放感あふれる緑のロケーション、そして真心込めたおもてなしで、皆様のお越しをお待ちしております',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => 'おふろcafé utatane',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 1,
            'zip' => '331-0815',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市北区大成町4丁目179-3',
            'access' => '大宮駅より埼玉新都市交通「ニューシャトル」 鉄道博物館駅（大成駅）より線路沿いを北に向かって徒歩約10分。国道17号線「大成橋南側」信号すぐ 首都高速「与野JCT」から約10分。 東北自動車道「岩槻IC」から約20分',
            'parking' => '有（無料）',
            'content' => 'あたたかいお風呂、おいしいごはん、ふかふかのソファー、明るい音楽。心とカラダがあたたまり、満ち足りる。誰もが特別な時間を過ごせるutataneで、笑顔あふれる素敵なひと時を。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '北浦和公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 1,
            'zip' => '330-0061',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市浦和区常盤9-30-1',
            'access' => 'JR北浦和駅西口から徒歩2分',
            'parking' => '近くの市営駐車場(有料)がご利用いただけます。',
            'content' => 'JR北浦和駅西口から徒歩2分の市街地に位置しています。昭和46年、埼玉大学の移転に伴い、大学跡地を公園として整備する計画が立てられました。昭和48年から整備をはじめ、翌49年に開設されました。また、昭和57年には、公園内に県立近代美術館がオープンしました。北浦和公園の南側はさいたま市の公園と接しており、2つの公園が一体となって公園が形成されています。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '見沼自然公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 1,
            'zip' => '336-0973',
            'prefecture' => '埼玉県',
            'address' => '埼玉県さいたま市緑区大字南部領辻450−１',
            'access' => 'JR「大宮駅」東口から国際興業バス「さいたま東営業所行き」「浦和美園駅西口行き」「浦和学院高校行き」「浦和東高校行き」乗車　「締切橋バス停」下車　徒歩約5分。JR「浦和駅」東口から「市立病院経由さいたま東営業所行き」乗車　「締切橋バス停」下車　徒歩約5分。埼玉高速鉄道「浦和美園駅」西口から国際興業バス「大宮駅東口行き」乗車　「締切橋バス停」下車　徒歩約5分',
            'parking' => '198台',
            'content' => 'さいたま市（旧大宮市・旧浦和市エリア）から川口市の埼玉県の中心部に広がる広大な田園地帯は、通称「見沼たんぼ」と呼ばれています。広大な「見沼たんぼ」にはすばらしい公園がたくさんあります。南部分に位置する「見沼自然公園」もそのひとつです。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '東武動物公園',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 61,
            'zip' => '345-0831',
            'prefecture' => '埼玉県',
            'address' => '埼玉県南埼玉郡宮代町大字須賀110',
            'access' => '東武伊勢崎線東武動物公園駅から徒歩で10分',
            'parking' => '西ゲート（動物園側）直営駐車場は、約3,000台駐車可能です。(有料)',
            'content' => '希少なホワイトタイガーをはじめ、全120種類1200頭の動物たちが飼育されており、エサやりなど動物と触れ合い体験もできて、見て楽しい触れて楽しい動物園です。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '国営武蔵丘陵森林公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 45,
            'zip' => '355-0802',
            'prefecture' => '埼玉県',
            'address' => '埼玉県比企郡滑川町大字山田1920',
            'access' => '東武東上線森林公園駅北口からバスで立正大学行きバスで約7分「滑川中学校」下車徒歩5分　公園南口行きバスで約7分（土日祝のみ） 関越自動車道東松山ICから車で熊谷方面へ約10分',
            'parking' => '有料駐車場あり',
            'content' => '公園内は、日本一大きなエアートランポリンのぽんぽこマウンテンやアスレチックコースなど、家族で体を思いっきり動かして遊べる遊具がたくさんあります。また、都市緑化植物園では、四季折々の風景や木々、草花もお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => 'ムーミンバレーパーク',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 8,
            'zip' => '357-0001',
            'prefecture' => '埼玉県',
            'address' => '埼玉県飯能市宮沢327-6',
            'access' => '飯能駅北口から宮沢湖入り口まで約3km (約10分)。飯能駅からバスで約13分',
            'parking' => '電車でのアクセスは、西武池袋線「飯能駅」北口、JR八高線「東飯能駅」東口から、バスで12分ほど（「東飯能駅」からのバスは土日のみ運行）。車でのアクセスも、圏央道・狭山日高ICから約12分',
            'content' => '「ムーミンバレーパーク」は、都心からおよそ50km、埼玉県の南西部に位置する“水と緑”が豊かな飯能市にオープンしました。森と水に囲まれたフィンランドの風土を演出するのにピッタリのロケーションで、都心から車や電車を使って1時間半ほどで気軽に行けるのも魅力的です。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null
​
          ],
          [
            'title' => '岩槻城址公園',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 1,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => 'さいたま市岩槻区太田3-4',
            'access' => '東北道岩槻ICから10分',
            'parking' => '無料あり',
            'content' => '県内三名城の一つといわれた岩槻城の城跡を整備して作られた約18万平方mの広い公園です。自然林に囲まれ起伏が多く、個人的には赤い八橋がお気に入りです。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '川越大師 喜多院',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 2,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '川越市小仙波町1-20-1',
            'access' => '川越ICより約20分',
            'parking' => '有料あり',
            'content' => '新しい朝の連続テレビ小説が始まる前に一度行っておきたかった川越の一番の観光スポット、喜多院です。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '熊谷スポーツ文化公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 3,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '熊谷市上川上300',
            'access' => '関越自動車道東松山I.Cから熊谷・東松山道路を熊谷方面へ約18km、または花園I.Cから国道140号を熊谷方面へ約16km。東北自動車道羽生I.Cから国道125号線を熊谷方面へ20km。R17バイパス肥塚信号北進３００メートル。',
            'parking' => '無料あり',
            'content' => '駐車場も施設も全て使用料が無料で１日遊べます、散歩道　ランニング道　アスレチック　池　などがありおおきな駐車場も全て無料です、池にはあひるや鯉　鴨も居ます、ただし飲み物の自販機しかないので食べ物などは入り口近くのコンビニで用意して下さい。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '川口市リサイクルプラザ',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 4,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '川口市朝日4-21-33',
            'access' => '首都高川口線「新郷」出入口から約5分',
            'parking' => '無料あり',
            'content' => 'ごみや環境について学んだ後で、プールでリフレッシュできます。子どもの教育をしながら、家族で楽しめる施設です。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '行田市郷土博物館',
            'theme' => '美術館・博物館',
            'category_id' => 4,
            'area_id' => 5,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '行田市本丸17-23',
            'access' => '東北自動車道「羽生IC」から約30分',
            'parking' => '無料あり',
            'content' => '映画のぼうの城の舞台になった忍城祉にある博物館で三階櫓や門などが再建されています。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '三峯神社（三峰神社）',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 6,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '秩父市三峰298-1',
            'access' => '関越自動車道・花園ICより国道140号線、皆野寄居バイパス経由で約2時間半。あるいは国道16号・入間市より国道299号＋国道140号経由で約3時間。中央自動車道・甲府昭和ICより国道140号線、雁坂トンネル経由で約2時間半。',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '多聞院',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 7,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '所沢市中富1501',
            'access' => '	関越自動車道所沢ICから約5㎞。 西武線所沢駅西口からバス、或いは東武東上線上福岡からバス。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '関八州見晴台',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 8,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '飯能市高山',
            'access' => '	圏央狭山日高ICから県347からR299飯能狭山BPを北西へ向かい、 吾野駅手前の借宿神社付近から川沿いを北上し高山不動尊へ。 その奥に見晴台入口の茶店(閉鎖？)があります。そこから徒歩約15分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'むさしの村',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 9,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '加須市志多見1700-1',
            'access' => '東北自動車道加須ＩＣから約２０分',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'こだま千本桜',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 10,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '本庄市児玉町',
            'access' => '	関越道本庄・児玉ICから約15分',
            'parking' => '無し',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '埼玉県こども動物自然公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 11,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '東松山市岩殿554',
            'access' => '関越自動車道、東松山ICから川越・川島方面へ降り、インター前交差点右折、Ｔ字路「米山大橋(北)」交差点を右折、次の信号「西本宿」を右折、直線１㎞。',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '藤花園（牛島の藤）',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 12,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '春日部市牛島786',
            'access' => '東北自動車道岩槻ICより約15km（約10分）。 常磐自動車道柏ICより約20km（約30分）。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '狭山市都市緑化植物園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 13,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '狭山市柏原622',
            'access' => '圏央道『狭山日高ＩＣ』から約5分。 国道１６号「狭山市入間川三丁目」交差点より。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '大天白神社（大天白公園）',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 14,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '羽生市北2丁目8-32',
            'access' => '東北自動車道「羽生IC」から約15分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'ポピー・ハッピースクエア',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 15,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '鴻巣市馬室555',
            'access' => '首都圏中央連絡自動車道川島ICより約20分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '高野精肉店',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 16,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '深谷市黒田985',
            'access' => '花園ICより10分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '上尾運動公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 17,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '上尾市愛宕三丁目',
            'access' => '首都高速大宮線新都心出口から熊谷方面に約１０ｋｍ',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '火あぶり地蔵尊',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 18,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '草加市瀬崎2丁目1',
            'access' => '県道足立越谷線を東京方面に向かい、県道松戸草加線との交差点（吉町五丁目交差点）',
            'parking' => '無し',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'オルタッジョ',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 19,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '越谷市流通団地3-2-1 越谷市場',
            'access' => '	JR武蔵野線「南越谷駅」から東へ20分程です。越谷市場内です。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '金亀山極楽寺三学院',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 20,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '蕨市北町３－２－４',
            'access' => 'ＪＲ蕨駅より１７分。外環浦和インターより。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '彩湖・道満グリーンパーク',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 21,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '戸田市大字重瀬７４５',
            'access' => '外環自動車道戸田東IC下りてすぐ',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '狭山茶の茶畑',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 22,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '入間市上谷ヶ貫',
            'access' => '圏央道入間ＩＣ～青梅ＩＣの間',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '陸上自衛隊広報センターりっくんランド',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 23,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '朝霞市栄町4-6',
            'access' => '東京外環自動車道「和光インター」から約1.5km',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '宝幢寺',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 24,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '志木市柏町1-10-22',
            'access' => '車で、首都高速5号池袋線「戸田南出口」から30分、首都高速埼玉大宮線「浦和南出口」から20分、関越自動車道「所沢IC」より12分、東京外環自走車道「和光北IC」より20分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '和光樹林公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 25,
            'zip' => '351-0106',
            'prefecture' => '埼玉県',
            'address' => '和光市広沢三番地内',
            'access' => '東武東上線、東京メトロ有楽町線・副都心線「和光市駅」から徒歩20分',
            'parking' => '有料あり',
            'content' => '和光樹林公園は、昭和20年米軍に接収された「キャンプ朝霞基地」の跡地の一部で、快適な住環境の確保と、美しい都市景観の創出を図る公園として、平成元年3月に開設された20.2haの公園です。多目的利用が可能な広場やジョギングコースなどがあるスポーツ・レクリエーションの場所として、また広域避難地として、県民に親しまれています。公園内に和光市総合体育館があり、都立大泉中央公園、練馬区立大泉さくら運動公園、陸上自衛隊朝霞駐屯地に隣接しています。なお、和光樹林公園内の一部は国有地の無償貸付を受けています。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'だちょう牧場　並木屋',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 26,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '新座市池田3-7-16',
            'access' => '川越街道（朝霞市）より車で１５分程度。最寄りの駅は西武池袋線「ひばりヶ丘」ですが、かなりの距離があり徒歩は不可です。関越自動車道新座料金所の横あたり。',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'ホンダエアポート・桶川スポーツランド',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 27,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '桶川市',
            'access' => '圏央道、川島から１０分',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '大輪神社',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 28,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '久喜市東大輪1713',
            'access' => '埼玉県道幸手加須バイパス線の産業団地北交差点付',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '北本自然観察公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 29,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '北本市荒井5-200',
            'access' => '東京方面からは首都高速埼玉線（Ｓ５）の与野インターから国道１７号線を熊谷方面へ。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '葛西用水路',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 30,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '草加市～八潮市間',
            'access' => '草加IC、または外環三郷西IC、八潮ICより。',
            'parking' => '無し',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '彩の国レストラン',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 31,
            'zip' => '354-8560',
            'prefecture' => '埼玉県',
            'address' => '富士見市山室１丁目１３１３ ららぽーと富士見',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '常磐自動車道',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 32,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '三郷市',
            'access' => '東京外環自動車道　や　首都高　から',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '蓮田SA',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 33,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '蓮田市',
            'access' => '東北自動車道、蓮田サービスエリア',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '顔振峠',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 34,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '飯能市',
            'access' => '国道２９９号を飯能から正丸峠、秩父方面へ向かいます。東吾野駅を過ぎて１０分後位に西武秩父線の陸橋をくぐり、さらに数分後にもう一度くぐります。２回目をくぐってすぐに右折。「顔振峠」の表示が出ています。後は山道を道なりに１５分程走ります。',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '権現堂堤（権現堂桜堤）',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 35,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '幸手市大字内国府間',
            'access' => '東北道加須ICから国道125号・4号経由約20分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '炭火串焼 パパん家',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 36,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '鶴ヶ島市大字鶴ヶ丘112-11',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'サイボク天然温泉　まきばの湯',
            'theme' => '温泉',
            'category_id' => 6,
            'area_id' => 37,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '日高市下大谷沢546',
            'access' => '圏央道狭山・日高ＩＣから川越方面へ下り、１つ目の信号を左折。国道４０７号線に入り田木交差点を右折し、道なりに約５分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'ブラッセリーミエル',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 38,
            'zip' => '342-0055',
            'prefecture' => '埼玉県',
            'address' => '吉川市吉川1-6-11',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '凱旋門',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 39,
            'zip' => '356-0050',
            'prefecture' => '埼玉県',
            'address' => 'ふじみ野市ふじみ野3-1-1',
            'access' => '',
            'parking' => '',
            'content' => '座敷席を備える古民家風の上品な店内で、近江牛の焼肉をはじめ、黒毛和牛を使用した各種の焼肉やホルモンを提供している。韓国料理もある。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'パワンナンハウス',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 40,
            'zip' => '349-0205',
            'prefecture' => '埼玉県',
            'address' => '白岡市西5-1-10',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '伊奈町町制施行記念公園（バラ園）',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 41,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '北足立郡伊奈町大字小針内宿732-1',
            'access' => '首都高速道路与野線『与野IC』より大宮バイパス～１７号線上尾駅入口より５分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '旧池上家住宅',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 42,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '入間郡三芳町大字竹間沢877',
            'access' => '関越自動車道｢所沢インターチェンジ｣から車で10分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '鎌北湖',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 43,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '入間郡毛呂山町大谷木字鎌北',
            'access' => '関越道鶴ヶ島ICから約30分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '越生梅林',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 44,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '入間郡越生町堂山',
            'access' => '関越自動車道：鶴ヶ島ICまたは東松山ICから、約30分。または、圏央道：圏央鶴ヶ島ICから、約30分',
            'parking' => '有料あり',
            'content' => '関東三大梅林の1つ、越生（おごせ）梅林。約2ヘクタールの園内には、白加賀、越生野梅、紅梅など1,000本もの梅が花を咲かせる。美しい景観とかぐわしい香りを楽しみながら、春の訪れを感じるドライブに出かけたい。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '二ノ宮山展望台',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 45,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '比企郡滑川町大字伊古',
            'access' => '関越自動車道　嵐山小川インターから　約10分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '嵐山渓谷',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 46,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '嵐山町大字鎌形2857',
            'access' => '練馬ICから関越で東松山ICを出て国道254号を10分ほど。',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '小川町腰越',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 47,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '比企郡小川町腰越',
            'access' => '小川町ICから10分',
            'parking' => '無し',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '平成の森公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 48,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '川島町大字下八ツ林920',
            'access' => '国道254号線、川島町「南園部」交差点より桶川方面へ。2つめの「下八ツ林」交差点を案内板にしたがって右折。500mほど先の左側。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '吉見運動総合公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 49,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '吉見町大字中曽根、一ツ木、地頭方、明秋、今泉ほか地内',
            'access' => '関越自動車道東松山ICから県道東松山鴻巣線を鴻巣方面に11km。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'JAXA地球観測センター',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 50,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '比企郡鳩山町大字大橋字沼ノ上1401',
            'access' => '関越自動車道｢鶴ヶ島IC｣から約10.6km',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '刈場坂峠',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 51,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '比企郡ときがわ町',
            'access' => '圏央道狭山日高ICから、国道２９９号線へ入り、飯能市内を抜けて秩父方面へ向かう。正丸トンネルに入る数十メートル手前の信号を斜め右へ曲がり、約５キロの山道を抜けて突き当たりが刈場坂峠です。',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '清泰山　西善寺',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 52,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '秩父郡横瀬町横瀬598',
            'access' => '車で飯能方面より国道299号線正丸峠～芦ヶ久保道の駅～横瀬へ約3分。 熊谷方面より国道140号線～秩父道の駅～国道299号線交差点横瀬方面へ約5分。西武線横瀬駅から車で5分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '秩父華厳の滝',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 53,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '秩父郡皆野町上日野沢',
            'access' => '皆野寄居有料道路終点より15分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'カヌーテ',
            'theme' => 'グルメ',
            'category_id' => 7,
            'area_id' => 54,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '秩父郡 長瀞町長瀞1458-6',
            'access' => '関越自動車道「花園IC」から約20分',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '小鹿野 両神山麓 花の郷（ダリア園）',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 55,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '秩父郡小鹿野町両神薄8160-1',
            'access' => '関越自動車道「花園IC」から国道140号経由、国道299号を小鹿野方面へ約42km、約70分。小鹿野町役場両神庁舎から約20分。',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '彩の国ふれあい牧場（秩父高原牧場）',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 56,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '秩父郡東秩父村坂本2951',
            'access' => '関越自動車道『嵐山小川IC』から約40分',
            'parking' => '無料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '円良田ハイキングコース',
            'theme' => '自然・風景',
            'category_id' => 1,
            'area_id' => 57,
            'zip' => '367-0194',
            'prefecture' => '埼玉県',
            'address' => '児玉郡美里町白石',
            'access' => 'ＪＲ八高線松久駅から車で15分',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '城峰公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 58,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '児玉郡神川町矢納 神川町矢納1277',
            'access' => '	関越自動車道・本庄・児玉I.C、藤岡・児玉方面へ下車し、国道462号線を神流町方面へ約40分',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '陽雲寺',
            'theme' => '建物・史跡',
            'category_id' => 2,
            'area_id' => 59,
            'zip' => '369-0301',
            'prefecture' => '埼玉県',
            'address' => '児玉郡上里町大字金久保701',
            'access' => '',
            'parking' => '不明',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => 'さいたま川の博物館',
            'theme' => '博物館・美術館',
            'category_id' => 4,
            'area_id' => 60,
            'zip' => '',
            'prefecture' => '埼玉県',
            'address' => '大里郡寄居町大字小園39',
            'access' => '関越道「花園IC」より約8分',
            'parking' => '有料あり',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '東武動物公園',
            'theme' => 'テーマパーク',
            'category_id' => 5,
            'area_id' => 61,
            'zip' => '345-0831',
            'prefecture' => '埼玉県',
            'address' => '南埼玉郡宮代町大字須賀110',
            'access' => '',
            'parking' => '有料あり',
            'content' => 'ハイブリッド・レジャーランド東武動物公園は、埼玉県南埼玉郡宮代町と白岡市にあるレジャーランド。総面積は関東最大級の61ha。また、動物園では国内第5位の入園者数である。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '杉戸天然温泉 雅楽の湯',
            'theme' => '温泉',
            'user_id' => 6,
            'area_id' => 62,
            'zip' => '345-0036',
            'prefecture' => '埼玉県',
            'address' => '埼玉県北葛飾郡杉戸町杉戸2517',
            'access' => '東武伊勢崎線「東武動物公園駅（東口）」より送迎バスあり。圏央道　幸手ICから約7分。東北自動車道 岩槻ＩＣから約30分。久喜ICから約20分。',
            'parking' => '170台(無料）',
            'content' => '埼玉県は東部。周囲を田園に囲まれたのどかな風景の中につくられた大露天風呂。四季を通じて味わえる美しい木々と杉戸の広い空を眺めながら、天然のなめらかな湯と自然を満喫して下さい。 露天風呂は、身体を芯から温められる「源泉あつ湯」、のんびりと贅沢に利用できる「生源泉つぼ風呂・石風呂」、きめ細かい炭酸ガスを天然温泉に溶かしこんだ「高濃度炭酸温泉」、他にも「岩風呂」「寝湯・寝ころび湯」と多彩。快適な湯めぐりをお楽しみいただけます。',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ],
          [
            'title' => '松伏総合公園',
            'theme' => '公園・植物園',
            'category_id' => 3,
            'area_id' => 63,
            'zip' => '343-0113',
            'prefecture' => '埼玉県',
            'address' => '北葛飾郡松伏町 ゆめみ野4-1',
            'access' => '',
            'parking' => '',
            'content' => '',
            'image_path1' => null,
            'image_path2' => null,
            'image_path3' => null,
            'likes_count' => 0,
            'created_at' => '2019-11-13',
            'updated_at' => null

          ]
        ]);
    }
}
